# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:53
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('csingle', 'ROOM_SINGLE'), ('cgroup', 'ROOM_GROUP')], db_index=True, max_length=20)),
                ('uid', models.CharField(max_length=250)),
                ('active_with', models.ManyToManyField(related_name='active_with', to='account.Account')),
                ('users', models.ManyToManyField(to='account.Account')),
            ],
            options={
                'db_table': 'chatroom',
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
